version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestNewP23Project
  gitServerName: p1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testnewp23.integrations:e2
  packages:
  - name: TestNewP23Project
    version: "1.0"
